pull_request_templates:
  - name: â™»ï¸ Feature / Enhancement
    file: feature.md
  - name: ğŸ› ï¸ Hotfix
    file: hotfix.md
  - name: ğŸš€ Major Version / Overhaul
    file: major.md
  - name: ğŸ§© Default Template
    file: default.md
